sudo: required

language: node_js

services:
  - docker

before_script:
  - docker build -t ninjaneers/wait-for-healthy .
  - docker run ninjaneers/wait-for-healthy
  - docker pull ninjaneers/semantic-release
  - docker run ninjaneers/semantic-release semantic-release